"""Numerical Python port of the MATLAB MCR-ALS toolbox."""

from .correlation import CorrelationResult, RegressionStats, yregrnew
from .kinetics import (
    KineticFitResult,
    KineticOptimizationResult,
    integrate_kinetics,
    interesp,
    kinetic_derivative,
    nglmglob,
    opt_kinglob,
    rcalcglob,
)

from .helpers import (
    EFAResult,
    closure,
    closurels,
    efa,
    fnnls,
    lof_quadrilinear,
    lof_trilinear,
    nnls,
    normv2,
    normv3,
    pcarep,
    pure,
    quadril,
    trilin,
    tuck2,
    unimod,
    wmat,
)
from .options import (
    ClosureBlock,
    ClosureCondition,
    ClosureOptions,
    CorrelationOptions,
    KineticModelOptions,
    KineticOptions,
    MCRALSOptions,
    MultiExperimentOptions,
    NonnegativityOptions,
    TrilinearityOptions,
    UnimodalityOptions,
    ValueConstraint,
    WeightedOptions,
    TuckerModeOptions,
    TuckerOptions,
)
from .solver import (
    IterationHistory,
    MCRALSResult,
    UnsupportedFeatureError,
    mcr_als,
)
from .weighted import MLPCAResult, mlpca

__all__ = [
    "ClosureBlock",
    "ClosureCondition",
    "ClosureOptions",
    "CorrelationOptions",
    "CorrelationResult",
    "EFAResult",
    "IterationHistory",
    "KineticFitResult",
    "KineticModelOptions",
    "KineticOptimizationResult",
    "KineticOptions",
    "MCRALSOptions",
    "MCRALSResult",
    "MLPCAResult",
    "MultiExperimentOptions",
    "NonnegativityOptions",
    "TrilinearityOptions",
    "TuckerModeOptions",
    "TuckerOptions",
    "RegressionStats",
    "UnimodalityOptions",
    "UnsupportedFeatureError",
    "ValueConstraint",
    "WeightedOptions",
    "closure",
    "closurels",
    "efa",
    "fnnls",
    "lof_quadrilinear",
    "lof_trilinear",
    "integrate_kinetics",
    "interesp",
    "kinetic_derivative",
    "nglmglob",
    "opt_kinglob",
    "mcr_als",
    "mlpca",
    "nnls",
    "normv2",
    "normv3",
    "pcarep",
    "pure",
    "quadril",
    "trilin",
    "tuck2",
    "rcalcglob",
    "unimod",
    "wmat",
    "yregrnew",
]
